[2025-04-10 22:30:56,601] - Exception Logger - ERROR - 'Collection' object is not callable. If you meant to call the 'insert_many' method on a 'Database' object it is failing because no such method exists. Occured in /home/gaurav/Documents/ModularCoding/main.py at 33
